import type {
  AuditLog,
  CashMovement,
  CashRegister,
  Customer,
  CustomerInteraction,
  Employee,
  FoodSafetyLog,
  InventoryMovement,
  Order,
  Product,
  ProductCategory,
  Purchase,
  PurchaseItem,
  RawMaterial,
  Recipe,
  Reservation,
  ReportPoint,
  RestaurantTable,
  Supplier,
} from "@/lib/types";

export const visualPanels = [
  {
    title: "Salon",
    subtitle: "Mapa de mesas y atencion presencial",
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Cocina",
    subtitle: "Comandas por estacion y tiempo real",
    image:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Caja",
    subtitle: "Apertura, pagos, propinas y cierre",
    image:
      "https://images.unsplash.com/photo-1556745757-8d76bdb6984b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Bodega",
    subtitle: "FIFO, vencimientos, mermas y compras",
    image:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80",
  },
];

export const productCategories: ProductCategory[] = [
  { id: "cat-main", name: "Fondos", color: "bg-red-500" },
  { id: "cat-starter", name: "Entradas", color: "bg-emerald-500" },
  { id: "cat-dessert", name: "Postres", color: "bg-fuchsia-500" },
  { id: "cat-bar", name: "Barra", color: "bg-cyan-500" },
];

export const suppliers: Supplier[] = [
  {
    id: "sup-1",
    name: "Carnes Andinas",
    category: "Carnes",
    contact: "Marcela Rivas",
    phone: "+56 9 4422 7811",
    reliability: 96,
    lastPurchase: "2026-05-07",
  },
  {
    id: "sup-2",
    name: "Costa Azul",
    category: "Pescados y mariscos",
    contact: "Ruben Soto",
    phone: "+56 9 5520 1140",
    reliability: 91,
    lastPurchase: "2026-05-08",
  },
  {
    id: "sup-3",
    name: "Huerta Local",
    category: "Verduras y frutas",
    contact: "Daniela Mena",
    phone: "+56 9 6711 9300",
    reliability: 94,
    lastPurchase: "2026-05-08",
  },
  {
    id: "sup-4",
    name: "Secos del Sur",
    category: "Abarrotes",
    contact: "Ignacio Palma",
    phone: "+56 9 3188 2018",
    reliability: 89,
    lastPurchase: "2026-05-06",
  },
];

export const rawMaterials: RawMaterial[] = [
  {
    id: "rm-lomo",
    name: "Lomo de vacuno",
    category: "meats",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 10000,
    stock: 7200,
    minStock: 3000,
    supplierId: "sup-1",
    averageYield: 70,
    storageTemperature: "0 a 4 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-12",
    sanitaryRisk: "high",
    lot: "CAR-0508-A",
    storageNotes: "Mantener en bandeja cubierta, separado de listos para consumo.",
  },
  {
    id: "rm-salmon",
    name: "Salmon fresco",
    category: "seafood",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 12800,
    stock: 3600,
    minStock: 2500,
    supplierId: "sup-2",
    averageYield: 78,
    storageTemperature: "0 a 2 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-10",
    sanitaryRisk: "high",
    lot: "PES-0508-S",
    storageNotes: "Usar antes de 48 horas, bandeja con drenaje.",
  },
  {
    id: "rm-camaron",
    name: "Camaron 36/40",
    category: "frozen",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 9400,
    stock: 5000,
    minStock: 1800,
    supplierId: "sup-2",
    averageYield: 82,
    storageTemperature: "-18 C",
    storageMethod: "FIFO",
    expirationDate: "2026-08-20",
    sanitaryRisk: "medium",
    lot: "CON-0428-C",
    storageNotes: "Descongelar en refrigeracion, nunca a temperatura ambiente.",
  },
  {
    id: "rm-cebolla",
    name: "Cebolla morada",
    category: "produce",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 1450,
    stock: 9200,
    minStock: 2500,
    supplierId: "sup-3",
    averageYield: 88,
    storageTemperature: "8 a 12 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-18",
    sanitaryRisk: "low",
    lot: "VER-0508-C",
    storageNotes: "Seco, ventilado, sin contacto con humedad.",
  },
  {
    id: "rm-palta",
    name: "Palta hass",
    category: "produce",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 4200,
    stock: 2600,
    minStock: 2000,
    supplierId: "sup-3",
    averageYield: 64,
    storageTemperature: "6 a 8 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-11",
    sanitaryRisk: "medium",
    lot: "VER-0508-P",
    storageNotes: "Controlar madurez diariamente.",
  },
  {
    id: "rm-queso",
    name: "Queso mantecoso",
    category: "dairy",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 6200,
    stock: 4200,
    minStock: 1800,
    supplierId: "sup-4",
    averageYield: 96,
    storageTemperature: "0 a 4 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-22",
    sanitaryRisk: "medium",
    lot: "LAC-0504-Q",
    storageNotes: "Conservar cerrado y rotulado despues de abrir.",
  },
  {
    id: "rm-arroz",
    name: "Arroz grano largo",
    category: "dry",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 1320,
    stock: 18000,
    minStock: 5000,
    supplierId: "sup-4",
    averageYield: 100,
    storageTemperature: "Ambiente seco",
    storageMethod: "FIFO",
    expirationDate: "2027-01-20",
    sanitaryRisk: "low",
    lot: "SEC-0420-A",
    storageNotes: "Mantener en contenedor hermetico rotulado.",
  },
  {
    id: "rm-crema",
    name: "Crema de leche",
    category: "dairy",
    unit: "ml",
    purchaseQuantity: 1000,
    purchaseCost: 3100,
    stock: 3500,
    minStock: 1500,
    supplierId: "sup-4",
    averageYield: 98,
    storageTemperature: "0 a 4 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-14",
    sanitaryRisk: "medium",
    lot: "LAC-0507-C",
    storageNotes: "Cerrar inmediatamente despues de uso.",
  },
  {
    id: "rm-harina",
    name: "Harina panadera",
    category: "allergens",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 980,
    stock: 15000,
    minStock: 4000,
    supplierId: "sup-4",
    averageYield: 99,
    storageTemperature: "Ambiente seco",
    storageMethod: "FIFO",
    expirationDate: "2026-10-01",
    sanitaryRisk: "low",
    lot: "ALG-0411-H",
    storageNotes: "Almacenar separado y rotulado como gluten.",
  },
];

export const inventoryMovements: InventoryMovement[] = [
  {
    id: "im-1",
    rawMaterialId: "rm-lomo",
    materialName: "Lomo de vacuno",
    type: "initial",
    quantity: 7200,
    unitCost: 14.29,
    reason: "Stock inicial academico",
    responsible: "Daniel Vega",
    time: "09:00",
    createdAt: "2026-05-08T09:00:00-04:00",
  },
  {
    id: "im-2",
    rawMaterialId: "rm-palta",
    materialName: "Palta hass",
    type: "waste",
    quantity: -320,
    unitCost: 6.56,
    reason: "Madurez avanzada",
    responsible: "Daniel Vega",
    time: "11:30",
    createdAt: "2026-05-08T11:30:00-04:00",
  },
  {
    id: "im-3",
    rawMaterialId: "rm-salmon",
    materialName: "Salmon fresco",
    type: "manual_out",
    quantity: -420,
    unitCost: 16.41,
    reason: "Mise en place cocina fria",
    responsible: "Rodrigo Fuentes",
    time: "12:15",
    createdAt: "2026-05-08T12:15:00-04:00",
  },
];

export const foodSafetyLogs: FoodSafetyLog[] = [
  {
    id: "fsl-1",
    rawMaterialId: "rm-salmon",
    materialName: "Salmon fresco",
    checkType: "Temperatura de recepcion",
    measuredTemperature: "1.8 C",
    result: "ok",
    notes: "Producto recibido frio, bandeja con drenaje y rotulo vigente.",
    responsible: "Daniel Vega",
    time: "10:20",
    createdAt: "2026-05-10T10:20:00-04:00",
  },
  {
    id: "fsl-2",
    rawMaterialId: "rm-palta",
    materialName: "Palta hass",
    checkType: "Control de vencimiento",
    measuredTemperature: "7 C",
    result: "warning",
    notes: "Madurez avanzada. Priorizar uso en mise en place de hoy.",
    responsible: "Rodrigo Fuentes",
    time: "11:35",
    createdAt: "2026-05-10T11:35:00-04:00",
  },
  {
    id: "fsl-3",
    rawMaterialId: "rm-harina",
    materialName: "Harina panadera",
    checkType: "Alergenos y rotulacion",
    measuredTemperature: "Ambiente seco",
    result: "ok",
    notes: "Contenedor cerrado, separado y rotulado como gluten.",
    responsible: "Daniel Vega",
    time: "12:05",
    createdAt: "2026-05-10T12:05:00-04:00",
  },
];

export const recipes: Recipe[] = [
  {
    id: "rec-lomo",
    name: "Lomo salteado de la casa",
    category: "Fondo caliente",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=80",
    portions: 4,
    prepTimeMinutes: 22,
    allergens: ["Soya", "Gluten"],
    procedure:
      "Limpiar lomo, cortar en bastones, sellar a alta temperatura, saltear vegetales y montar con arroz.",
    observations:
      "Controlar punto de coccion y no sobrecargar el sarten para evitar perdida de jugos.",
    targetFoodCostPercent: 30,
    salePrice: 14900,
    ingredients: [
      {
        id: "ri-1",
        rawMaterialId: "rm-lomo",
        name: "Lomo limpio",
        unit: "g",
        grossQuantity: 860,
        yieldPercent: 70,
        wasteType: "Limpieza y despunte",
      },
      {
        id: "ri-2",
        rawMaterialId: "rm-cebolla",
        name: "Cebolla morada",
        unit: "g",
        grossQuantity: 240,
        yieldPercent: 88,
        wasteType: "Piel y raiz",
      },
      {
        id: "ri-3",
        rawMaterialId: "rm-arroz",
        name: "Arroz cocido base",
        unit: "g",
        grossQuantity: 420,
        yieldPercent: 100,
        wasteType: "Sin merma",
      },
    ],
  },
  {
    id: "rec-salmon",
    name: "Salmon grillado con crema citrica",
    category: "Fondo pescado",
    image:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80",
    portions: 3,
    prepTimeMinutes: 18,
    allergens: ["Pescado", "Lacteos"],
    procedure:
      "Porcionar salmon, grillar por piel, reducir crema citrica y servir con vegetales.",
    observations:
      "Mantener cadena de frio y controlar coccion para evitar resecado.",
    targetFoodCostPercent: 32,
    salePrice: 16900,
    ingredients: [
      {
        id: "ri-4",
        rawMaterialId: "rm-salmon",
        name: "Filete de salmon",
        unit: "g",
        grossQuantity: 640,
        yieldPercent: 78,
        wasteType: "Piel, espinas y recorte",
      },
      {
        id: "ri-5",
        rawMaterialId: "rm-crema",
        name: "Crema de leche",
        unit: "ml",
        grossQuantity: 280,
        yieldPercent: 92,
        wasteType: "Reduccion por evaporacion",
      },
    ],
  },
  {
    id: "rec-entrada",
    name: "Causa fria de camaron y palta",
    category: "Entrada fria",
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80",
    portions: 6,
    prepTimeMinutes: 16,
    allergens: ["Mariscos"],
    procedure:
      "Cocer base, prensar, montar con camaron descongelado en frio y palta laminada.",
    observations:
      "Mantener en frio hasta servicio y registrar lote de marisco.",
    targetFoodCostPercent: 28,
    salePrice: 8900,
    ingredients: [
      {
        id: "ri-6",
        rawMaterialId: "rm-camaron",
        name: "Camaron limpio",
        unit: "g",
        grossQuantity: 520,
        yieldPercent: 82,
        wasteType: "Glaseo y descongelado",
      },
      {
        id: "ri-7",
        rawMaterialId: "rm-palta",
        name: "Palta hass",
        unit: "g",
        grossQuantity: 460,
        yieldPercent: 64,
        wasteType: "Carozo y cascara",
      },
    ],
  },
];

export const products: Product[] = [
  {
    id: "prod-lomo",
    name: "Lomo salteado",
    categoryId: "cat-main",
    description: "Lomo, arroz, cebolla morada, salsa de la casa.",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=80",
    price: 14900,
    available: true,
    prepTimeMinutes: 22,
    recipeId: "rec-lomo",
    modifiers: ["Sin cebolla", "Punto medio", "Bien cocido", "Extra queso"],
  },
  {
    id: "prod-salmon",
    name: "Salmon grillado",
    categoryId: "cat-main",
    description: "Salmon fresco, crema citrica y vegetales.",
    image:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80",
    price: 16900,
    available: true,
    prepTimeMinutes: 18,
    recipeId: "rec-salmon",
    modifiers: ["Sin lacteos", "Punto jugoso", "Punto cocido"],
  },
  {
    id: "prod-causa",
    name: "Causa camaron palta",
    categoryId: "cat-starter",
    description: "Entrada fria con camaron, palta y base especiada.",
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80",
    price: 8900,
    available: true,
    prepTimeMinutes: 16,
    recipeId: "rec-entrada",
    modifiers: ["Sin palta", "Extra camaron", "Sin picante"],
  },
  {
    id: "prod-tabla",
    name: "Tabla caliente",
    categoryId: "cat-starter",
    description: "Porciones para compartir, salsas y panes.",
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
    price: 18900,
    available: false,
    prepTimeMinutes: 25,
    modifiers: ["Sin gluten", "Extra salsa", "Sin queso"],
  },
  {
    id: "prod-jugo",
    name: "Jugo natural",
    categoryId: "cat-bar",
    description: "Fruta fresca de temporada.",
    image:
      "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=900&q=80",
    price: 3900,
    available: true,
    prepTimeMinutes: 5,
    modifiers: ["Sin azucar", "Con hielo", "Sin hielo"],
  },
];

export const restaurantTables: RestaurantTable[] = [
  {
    id: "t-1",
    number: 1,
    seats: 2,
    zone: "Terraza",
    status: "free",
    server: "Valentina",
  },
  {
    id: "t-2",
    number: 2,
    seats: 4,
    zone: "Terraza",
    status: "occupied",
    server: "Valentina",
    currentOrderId: "ord-1",
    elapsedMinutes: 26,
    total: 42600,
  },
  {
    id: "t-3",
    number: 3,
    seats: 6,
    zone: "Salon",
    status: "reserved",
    server: "Matias",
  },
  {
    id: "t-4",
    number: 4,
    seats: 4,
    zone: "Salon",
    status: "occupied",
    server: "Camila",
    currentOrderId: "ord-2",
    elapsedMinutes: 14,
    total: 33800,
  },
  {
    id: "t-5",
    number: 5,
    seats: 2,
    zone: "Salon",
    status: "cleaning",
    server: "Camila",
    elapsedMinutes: 5,
  },
  {
    id: "t-6",
    number: 6,
    seats: 8,
    zone: "Comedor",
    status: "free",
    server: "Matias",
  },
  {
    id: "t-7",
    number: 7,
    seats: 4,
    zone: "Comedor",
    status: "occupied",
    server: "Valentina",
    currentOrderId: "ord-3",
    elapsedMinutes: 38,
    total: 57200,
  },
  {
    id: "t-8",
    number: 8,
    seats: 4,
    zone: "Comedor",
    status: "free",
    server: "Camila",
  },
  {
    id: "t-9",
    number: 9,
    seats: 2,
    zone: "Barra",
    status: "reserved",
    server: "Matias",
  },
  {
    id: "t-10",
    number: 10,
    seats: 4,
    zone: "Barra",
    status: "free",
    server: "Valentina",
  },
  {
    id: "t-11",
    number: 11,
    seats: 6,
    zone: "Salon",
    status: "free",
    server: "Camila",
  },
  {
    id: "t-12",
    number: 12,
    seats: 2,
    zone: "Salon",
    status: "occupied",
    server: "Matias",
    currentOrderId: "ord-4",
    elapsedMinutes: 8,
    total: 23800,
  },
];

export const orders: Order[] = [
  {
    id: "ord-1",
    number: "A-1048",
    tableNumber: 2,
    status: "preparing",
    waiter: "Valentina",
    createdAt: "2026-05-08T13:42:00-04:00",
    discount: 0,
    tip: 4260,
    total: 42600,
    items: [
      {
        id: "oi-1",
        productId: "prod-lomo",
        productName: "Lomo salteado",
        quantity: 2,
        unitPrice: 14900,
        modifiers: ["Punto medio", "Sin cebolla"],
        notes: "Mesa apurada, enviar fondos juntos.",
        station: "hot",
      },
      {
        id: "oi-2",
        productId: "prod-jugo",
        productName: "Jugo natural",
        quantity: 2,
        unitPrice: 3900,
        modifiers: ["Sin azucar"],
        station: "bar",
      },
    ],
  },
  {
    id: "ord-2",
    number: "A-1049",
    tableNumber: 4,
    status: "pending",
    waiter: "Camila",
    createdAt: "2026-05-08T13:54:00-04:00",
    discount: 1500,
    tip: 3380,
    total: 33800,
    items: [
      {
        id: "oi-3",
        productId: "prod-salmon",
        productName: "Salmon grillado",
        quantity: 2,
        unitPrice: 16900,
        modifiers: ["Punto jugoso"],
        notes: "Uno sin salsa sobre el plato.",
        station: "hot",
      },
    ],
  },
  {
    id: "ord-3",
    number: "A-1050",
    tableNumber: 7,
    status: "ready",
    waiter: "Valentina",
    createdAt: "2026-05-08T13:30:00-04:00",
    discount: 0,
    tip: 5720,
    total: 57200,
    items: [
      {
        id: "oi-4",
        productId: "prod-causa",
        productName: "Causa camaron palta",
        quantity: 4,
        unitPrice: 8900,
        modifiers: ["Extra camaron"],
        station: "cold",
      },
      {
        id: "oi-5",
        productId: "prod-jugo",
        productName: "Jugo natural",
        quantity: 4,
        unitPrice: 3900,
        modifiers: ["Con hielo"],
        station: "bar",
      },
    ],
  },
  {
    id: "ord-4",
    number: "A-1051",
    tableNumber: 12,
    status: "pending",
    waiter: "Matias",
    createdAt: "2026-05-08T14:02:00-04:00",
    discount: 0,
    tip: 2380,
    total: 23800,
    items: [
      {
        id: "oi-6",
        productId: "prod-lomo",
        productName: "Lomo salteado",
        quantity: 1,
        unitPrice: 14900,
        modifiers: ["Bien cocido", "Extra queso"],
        notes: "Alergia declarada a mariscos.",
        station: "hot",
      },
      {
        id: "oi-7",
        productId: "prod-causa",
        productName: "Causa camaron palta",
        quantity: 1,
        unitPrice: 8900,
        modifiers: ["Sin palta"],
        station: "cold",
      },
    ],
  },
];

export const employees: Employee[] = [
  {
    id: "emp-1",
    name: "Paula Contreras",
    role: "administrator",
    rut: "12.345.678-5",
    phone: "+56 9 7000 1101",
    shift: "Administracion",
    hourlyCost: 11500,
    status: "active",
    hiredAt: "2024-03-01",
    sales: 0,
    orders: 0,
  },
  {
    id: "emp-2",
    name: "Rodrigo Fuentes",
    role: "chef",
    rut: "13.222.111-9",
    phone: "+56 9 7000 1102",
    shift: "Cocina AM",
    hourlyCost: 9800,
    status: "active",
    hiredAt: "2024-04-15",
    sales: 0,
    orders: 18,
    kitchenAverage: 17,
  },
  {
    id: "emp-3",
    name: "Valentina Reyes",
    role: "waiter",
    rut: "18.445.120-2",
    phone: "+56 9 7000 1103",
    shift: "Salon AM",
    hourlyCost: 5200,
    status: "active",
    hiredAt: "2025-01-10",
    sales: 184700,
    orders: 12,
  },
  {
    id: "emp-4",
    name: "Camila Soto",
    role: "waiter",
    rut: "19.002.441-7",
    phone: "+56 9 7000 1104",
    shift: "Salon AM",
    hourlyCost: 5200,
    status: "break",
    hiredAt: "2025-02-03",
    sales: 126900,
    orders: 8,
  },
  {
    id: "emp-5",
    name: "Felipe Araya",
    role: "cashier",
    rut: "16.778.901-3",
    phone: "+56 9 7000 1105",
    shift: "Caja AM",
    hourlyCost: 6100,
    status: "active",
    hiredAt: "2024-11-20",
    sales: 311600,
    orders: 24,
  },
  {
    id: "emp-6",
    name: "Daniel Vega",
    role: "warehouse",
    rut: "15.994.200-8",
    phone: "+56 9 7000 1106",
    shift: "Bodega",
    hourlyCost: 6400,
    status: "active",
    hiredAt: "2024-08-05",
    sales: 0,
    orders: 0,
  },
];

export const customers: Customer[] = [
  {
    id: "cust-1",
    name: "Carolina Munoz",
    phone: "+56 9 8111 2001",
    email: "carolina.munoz@example.com",
    documentId: "17.440.221-5",
    preferences: "Prefiere terraza, vinos blancos y platos sin lacteos.",
    allergies: ["Lacteos"],
    tags: ["Frecuente", "Cumpleanos"],
    visitCount: 8,
    totalSpent: 426800,
    lastVisitAt: "2026-05-03T21:10:00-04:00",
    notes: "Solicitar confirmacion por WhatsApp el mismo dia.",
    createdAt: "2025-11-12T10:30:00-03:00",
  },
  {
    id: "cust-2",
    name: "Andres Salinas",
    phone: "+56 9 8222 2002",
    email: "andres.salinas@example.com",
    documentId: "14.202.118-0",
    preferences: "Mesa tranquila, sin picante, agua sin gas.",
    allergies: ["Mariscos"],
    tags: ["Alergia declarada", "Empresa"],
    visitCount: 4,
    totalSpent: 281500,
    lastVisitAt: "2026-04-29T14:20:00-04:00",
    notes: "Registrar alerta de alergia en comandas.",
    createdAt: "2026-01-18T09:15:00-03:00",
  },
  {
    id: "cust-3",
    name: "Isidora Paredes",
    phone: "+56 9 8333 2003",
    email: "isidora.paredes@example.com",
    documentId: "20.341.908-6",
    preferences: "Celebraciones pequenas, postres para compartir.",
    allergies: [],
    tags: ["Reserva web", "Familia"],
    visitCount: 2,
    totalSpent: 137900,
    lastVisitAt: "2026-04-12T16:40:00-04:00",
    notes: "Prefiere confirmacion por email.",
    createdAt: "2026-03-02T16:40:00-03:00",
  },
  {
    id: "cust-4",
    name: "Matias Vergara",
    phone: "+56 9 8444 2004",
    email: "matias.vergara@example.com",
    documentId: "16.902.118-4",
    preferences: "Barra, jugos naturales, opciones vegetarianas.",
    allergies: [],
    tags: ["Nuevo", "Barra"],
    visitCount: 1,
    totalSpent: 38900,
    lastVisitAt: "2026-05-09T19:25:00-04:00",
    notes: "Invitar a programa de fidelizacion.",
    createdAt: "2026-05-09T19:25:00-04:00",
  },
];

export const reservations: Reservation[] = [
  {
    id: "res-1",
    customerId: "cust-1",
    customerName: "Carolina Munoz",
    customerPhone: "+56 9 8111 2001",
    tableId: "t-3",
    tableNumber: 3,
    partySize: 6,
    date: "2026-05-10",
    time: "20:30",
    status: "confirmed",
    channel: "whatsapp",
    occasion: "Cumpleanos",
    notes: "Preparar mesa con espacio para torta. Sin lacteos.",
    assignedTo: "Valentina Reyes",
    createdAt: "2026-05-09T11:20:00-04:00",
  },
  {
    id: "res-2",
    customerId: "cust-2",
    customerName: "Andres Salinas",
    customerPhone: "+56 9 8222 2002",
    tableId: "t-9",
    tableNumber: 9,
    partySize: 2,
    date: "2026-05-10",
    time: "13:45",
    status: "seated",
    channel: "phone",
    occasion: "Almuerzo empresa",
    notes: "Alergia a mariscos. Confirmar con cocina antes de enviar.",
    assignedTo: "Camila Soto",
    createdAt: "2026-05-10T09:10:00-04:00",
  },
  {
    id: "res-3",
    customerId: "cust-3",
    customerName: "Isidora Paredes",
    customerPhone: "+56 9 8333 2003",
    tableId: "t-11",
    tableNumber: 11,
    partySize: 5,
    date: "2026-05-11",
    time: "21:00",
    status: "pending",
    channel: "web",
    occasion: "Cena familiar",
    notes: "Pendiente confirmar asistencia antes de las 17:00.",
    assignedTo: "Valentina Reyes",
    createdAt: "2026-05-10T12:10:00-04:00",
  },
  {
    id: "res-4",
    customerId: "cust-4",
    customerName: "Matias Vergara",
    customerPhone: "+56 9 8444 2004",
    tableId: "t-10",
    tableNumber: 10,
    partySize: 2,
    date: "2026-05-10",
    time: "19:00",
    status: "cancelled",
    channel: "walk_in",
    occasion: "Sin ocasion",
    notes: "Cancelada por cambio de horario.",
    assignedTo: "Felipe Araya",
    createdAt: "2026-05-10T15:30:00-04:00",
  },
];

export const customerInteractions: CustomerInteraction[] = [
  {
    id: "ci-1",
    customerId: "cust-1",
    customerName: "Carolina Munoz",
    type: "message",
    summary: "Confirmacion enviada por WhatsApp para reserva de cumpleanos.",
    completedAt: "2026-05-10T11:30:00-04:00",
    responsible: "Valentina Reyes",
    createdAt: "2026-05-10T11:30:00-04:00",
  },
  {
    id: "ci-2",
    customerId: "cust-2",
    customerName: "Andres Salinas",
    type: "preference",
    summary: "Se reforzo alerta de alergia a mariscos en ficha y reserva.",
    completedAt: "2026-05-10T09:15:00-04:00",
    responsible: "Camila Soto",
    createdAt: "2026-05-10T09:15:00-04:00",
  },
  {
    id: "ci-3",
    customerId: "cust-3",
    customerName: "Isidora Paredes",
    type: "follow_up",
    summary: "Confirmar asistencia y cantidad final de comensales.",
    dueAt: "2026-05-11T17:00:00-04:00",
    responsible: "Valentina Reyes",
    createdAt: "2026-05-10T12:15:00-04:00",
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: "aud-0",
    action: "reservation.upsert",
    entityType: "reservation",
    entityId: "res-1",
    summary: "Reserva confirmada para Carolina Munoz.",
    actor: "Valentina Reyes",
    actorRole: "waiter",
    metadata: { date: "2026-05-10", time: "20:30", partySize: 6 },
    time: "11:20",
    createdAt: "2026-05-10T11:20:00-04:00",
  },
  {
    id: "aud-1",
    action: "cash.payment.settle",
    entityType: "order",
    entityId: "ord-3",
    summary: "Cuenta A-1050 cobrada con debito y descuento de inventario.",
    actor: "Felipe Araya",
    actorRole: "cashier",
    metadata: { paymentMethod: "debit", amount: 57200, table: 7 },
    time: "12:35",
    createdAt: "2026-05-10T12:35:00-04:00",
  },
  {
    id: "aud-2",
    action: "inventory.movement.create",
    entityType: "raw_material",
    entityId: "rm-palta",
    summary: "Merma registrada por madurez avanzada.",
    actor: "Daniel Vega",
    actorRole: "warehouse",
    metadata: { movementType: "waste", quantity: -320 },
    time: "11:30",
    createdAt: "2026-05-10T11:30:00-04:00",
  },
  {
    id: "aud-3",
    action: "food_safety.check.create",
    entityType: "raw_material",
    entityId: "rm-salmon",
    summary: "Control sanitario conforme para Salmon fresco.",
    actor: "Daniel Vega",
    actorRole: "warehouse",
    metadata: { result: "ok", temperature: "1.8 C" },
    time: "10:20",
    createdAt: "2026-05-10T10:20:00-04:00",
  },
  {
    id: "aud-4",
    action: "recipe.upsert",
    entityType: "recipe",
    entityId: "rec-lomo",
    summary: "Receta tecnica actualizada con rendimiento y food cost objetivo.",
    actor: "Rodrigo Fuentes",
    actorRole: "chef",
    metadata: { targetFoodCostPercent: 30, portions: 4 },
    time: "09:45",
    createdAt: "2026-05-10T09:45:00-04:00",
  },
];

export const purchaseItems: PurchaseItem[] = [
  {
    id: "pi-1",
    purchaseId: "pur-1",
    rawMaterialId: "rm-lomo",
    materialName: "Lomo de vacuno",
    description: "Lomo de vacuno caja AM",
    quantity: 12000,
    unit: "g",
    unitCost: 15.33,
    yieldPercent: 70,
    totalCost: 184000,
    expirationDate: "2026-05-12",
    lot: "CAR-0508-A",
  },
  {
    id: "pi-2",
    purchaseId: "pur-2",
    rawMaterialId: "rm-salmon",
    materialName: "Salmon fresco",
    description: "Salmon fresco filete",
    quantity: 9000,
    unit: "g",
    unitCost: 15.96,
    yieldPercent: 78,
    totalCost: 143600,
    expirationDate: "2026-05-10",
    lot: "PES-0508-S",
  },
  {
    id: "pi-3",
    purchaseId: "pur-3",
    rawMaterialId: "rm-palta",
    materialName: "Palta hass",
    description: "Palta hass malla",
    quantity: 11571,
    unit: "g",
    unitCost: 4.2,
    yieldPercent: 64,
    totalCost: 48600,
    expirationDate: "2026-05-11",
    lot: "VER-0508-P",
  },
];

export const purchases: Purchase[] = [
  {
    id: "pur-1",
    supplierId: "sup-1",
    supplierName: "Carnes Andinas",
    documentType: "invoice",
    documentNumber: "F-88219",
    date: "2026-05-07",
    total: 184000,
    status: "received",
    items: purchaseItems.filter((item) => item.purchaseId === "pur-1"),
  },
  {
    id: "pur-2",
    supplierId: "sup-2",
    supplierName: "Costa Azul",
    documentType: "invoice",
    documentNumber: "F-22018",
    date: "2026-05-08",
    total: 143600,
    status: "priced",
    items: purchaseItems.filter((item) => item.purchaseId === "pur-2"),
  },
  {
    id: "pur-3",
    supplierId: "sup-3",
    supplierName: "Huerta Local",
    documentType: "receipt",
    documentNumber: "B-5518",
    date: "2026-05-08",
    total: 48600,
    status: "received",
    items: purchaseItems.filter((item) => item.purchaseId === "pur-3"),
  },
];

export const cashMovements: CashMovement[] = [
  {
    id: "cm-1",
    type: "opening",
    description: "Apertura turno AM",
    method: "internal",
    amount: 120000,
    time: "09:00",
    responsible: "Felipe Araya",
  },
  {
    id: "cm-2",
    type: "sale",
    description: "Pago mesa 7",
    method: "debit",
    amount: 57200,
    time: "13:59",
    responsible: "Felipe Araya",
  },
  {
    id: "cm-3",
    type: "tip",
    description: "Propina mesa 7",
    method: "debit",
    amount: 5720,
    time: "13:59",
    responsible: "Felipe Araya",
  },
  {
    id: "cm-4",
    type: "withdrawal",
    description: "Retiro caja chica",
    method: "cash",
    amount: -20000,
    time: "14:10",
    responsible: "Supervisor",
  },
  {
    id: "cm-5",
    type: "advance",
    description: "Adelanto autorizado",
    method: "cash",
    amount: -15000,
    time: "14:15",
    responsible: "Supervisor",
  },
];

export const cashRegisters: CashRegister[] = [
  {
    id: "cr-1",
    openingAmount: 120000,
    expectedAmount: 277200,
    status: "open",
    openedAt: "2026-05-08T09:00:00-04:00",
    openedBy: "Felipe Araya",
    notes: "Turno AM",
  },
];

export const reportPoints: ReportPoint[] = [
  { label: "Lun", sales: 780000, foodCost: 248000, margin: 532000, orders: 74 },
  { label: "Mar", sales: 692000, foodCost: 226000, margin: 466000, orders: 68 },
  { label: "Mie", sales: 834000, foodCost: 257000, margin: 577000, orders: 81 },
  { label: "Jue", sales: 910000, foodCost: 293000, margin: 617000, orders: 88 },
  { label: "Vie", sales: 1134000, foodCost: 352000, margin: 782000, orders: 106 },
  { label: "Sab", sales: 1286000, foodCost: 398000, margin: 888000, orders: 119 },
  { label: "Dom", sales: 972000, foodCost: 301000, margin: 671000, orders: 92 },
];

export const educationSteps = [
  "Configurar roles y permisos antes de iniciar el turno.",
  "Crear mesas, asignar mesero y abrir pedido presencial.",
  "Agregar productos con modificadores y observaciones.",
  "Enviar comanda a cocina y medir tiempos por estacion.",
  "Cerrar cuenta con pago, propina, descuento y diferencia de caja.",
  "Revisar salida automatica de inventario y mermas.",
  "Comparar costo tecnico, precio sugerido y rentabilidad real.",
];
