import type {
  CashMovement,
  Employee,
  Order,
  Product,
  ProductCategory,
  Purchase,
  RawMaterial,
  Recipe,
  ReportPoint,
  RestaurantTable,
  Supplier,
} from "@/lib/types";

export const visualPanels = [
  {
    title: "Salon",
    subtitle: "Mapa de mesas y atencion presencial",
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Cocina",
    subtitle: "Comandas por estacion y tiempo real",
    image:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Caja",
    subtitle: "Apertura, pagos, propinas y cierre",
    image:
      "https://images.unsplash.com/photo-1556745757-8d76bdb6984b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    title: "Bodega",
    subtitle: "FIFO, vencimientos, mermas y compras",
    image:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80",
  },
];

export const productCategories: ProductCategory[] = [
  { id: "cat-main", name: "Fondos", color: "bg-red-500" },
  { id: "cat-starter", name: "Entradas", color: "bg-emerald-500" },
  { id: "cat-dessert", name: "Postres", color: "bg-fuchsia-500" },
  { id: "cat-bar", name: "Barra", color: "bg-cyan-500" },
];

export const suppliers: Supplier[] = [
  {
    id: "sup-1",
    name: "Carnes Andinas",
    category: "Carnes",
    contact: "Marcela Rivas",
    phone: "+56 9 4422 7811",
    reliability: 96,
    lastPurchase: "2026-05-07",
  },
  {
    id: "sup-2",
    name: "Costa Azul",
    category: "Pescados y mariscos",
    contact: "Ruben Soto",
    phone: "+56 9 5520 1140",
    reliability: 91,
    lastPurchase: "2026-05-08",
  },
  {
    id: "sup-3",
    name: "Huerta Local",
    category: "Verduras y frutas",
    contact: "Daniela Mena",
    phone: "+56 9 6711 9300",
    reliability: 94,
    lastPurchase: "2026-05-08",
  },
  {
    id: "sup-4",
    name: "Secos del Sur",
    category: "Abarrotes",
    contact: "Ignacio Palma",
    phone: "+56 9 3188 2018",
    reliability: 89,
    lastPurchase: "2026-05-06",
  },
];

export const rawMaterials: RawMaterial[] = [
  {
    id: "rm-lomo",
    name: "Lomo de vacuno",
    category: "meats",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 10000,
    stock: 7200,
    minStock: 3000,
    supplierId: "sup-1",
    averageYield: 70,
    storageTemperature: "0 a 4 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-12",
    sanitaryRisk: "high",
    lot: "CAR-0508-A",
    storageNotes: "Mantener en bandeja cubierta, separado de listos para consumo.",
  },
  {
    id: "rm-salmon",
    name: "Salmon fresco",
    category: "seafood",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 12800,
    stock: 3600,
    minStock: 2500,
    supplierId: "sup-2",
    averageYield: 78,
    storageTemperature: "0 a 2 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-10",
    sanitaryRisk: "high",
    lot: "PES-0508-S",
    storageNotes: "Usar antes de 48 horas, bandeja con drenaje.",
  },
  {
    id: "rm-camaron",
    name: "Camaron 36/40",
    category: "frozen",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 9400,
    stock: 5000,
    minStock: 1800,
    supplierId: "sup-2",
    averageYield: 82,
    storageTemperature: "-18 C",
    storageMethod: "FIFO",
    expirationDate: "2026-08-20",
    sanitaryRisk: "medium",
    lot: "CON-0428-C",
    storageNotes: "Descongelar en refrigeracion, nunca a temperatura ambiente.",
  },
  {
    id: "rm-cebolla",
    name: "Cebolla morada",
    category: "produce",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 1450,
    stock: 9200,
    minStock: 2500,
    supplierId: "sup-3",
    averageYield: 88,
    storageTemperature: "8 a 12 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-18",
    sanitaryRisk: "low",
    lot: "VER-0508-C",
    storageNotes: "Seco, ventilado, sin contacto con humedad.",
  },
  {
    id: "rm-palta",
    name: "Palta hass",
    category: "produce",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 4200,
    stock: 2600,
    minStock: 2000,
    supplierId: "sup-3",
    averageYield: 64,
    storageTemperature: "6 a 8 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-11",
    sanitaryRisk: "medium",
    lot: "VER-0508-P",
    storageNotes: "Controlar madurez diariamente.",
  },
  {
    id: "rm-queso",
    name: "Queso mantecoso",
    category: "dairy",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 6200,
    stock: 4200,
    minStock: 1800,
    supplierId: "sup-4",
    averageYield: 96,
    storageTemperature: "0 a 4 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-22",
    sanitaryRisk: "medium",
    lot: "LAC-0504-Q",
    storageNotes: "Conservar cerrado y rotulado despues de abrir.",
  },
  {
    id: "rm-arroz",
    name: "Arroz grano largo",
    category: "dry",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 1320,
    stock: 18000,
    minStock: 5000,
    supplierId: "sup-4",
    averageYield: 100,
    storageTemperature: "Ambiente seco",
    storageMethod: "FIFO",
    expirationDate: "2027-01-20",
    sanitaryRisk: "low",
    lot: "SEC-0420-A",
    storageNotes: "Mantener en contenedor hermetico rotulado.",
  },
  {
    id: "rm-crema",
    name: "Crema de leche",
    category: "dairy",
    unit: "ml",
    purchaseQuantity: 1000,
    purchaseCost: 3100,
    stock: 3500,
    minStock: 1500,
    supplierId: "sup-4",
    averageYield: 98,
    storageTemperature: "0 a 4 C",
    storageMethod: "FIFO",
    expirationDate: "2026-05-14",
    sanitaryRisk: "medium",
    lot: "LAC-0507-C",
    storageNotes: "Cerrar inmediatamente despues de uso.",
  },
  {
    id: "rm-harina",
    name: "Harina panadera",
    category: "allergens",
    unit: "g",
    purchaseQuantity: 1000,
    purchaseCost: 980,
    stock: 15000,
    minStock: 4000,
    supplierId: "sup-4",
    averageYield: 99,
    storageTemperature: "Ambiente seco",
    storageMethod: "FIFO",
    expirationDate: "2026-10-01",
    sanitaryRisk: "low",
    lot: "ALG-0411-H",
    storageNotes: "Almacenar separado y rotulado como gluten.",
  },
];

export const recipes: Recipe[] = [
  {
    id: "rec-lomo",
    name: "Lomo salteado de la casa",
    category: "Fondo caliente",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=80",
    portions: 4,
    prepTimeMinutes: 22,
    allergens: ["Soya", "Gluten"],
    procedure:
      "Limpiar lomo, cortar en bastones, sellar a alta temperatura, saltear vegetales y montar con arroz.",
    observations:
      "Controlar punto de coccion y no sobrecargar el sarten para evitar perdida de jugos.",
    targetFoodCostPercent: 30,
    salePrice: 14900,
    ingredients: [
      {
        id: "ri-1",
        rawMaterialId: "rm-lomo",
        name: "Lomo limpio",
        unit: "g",
        grossQuantity: 860,
        yieldPercent: 70,
        wasteType: "Limpieza y despunte",
      },
      {
        id: "ri-2",
        rawMaterialId: "rm-cebolla",
        name: "Cebolla morada",
        unit: "g",
        grossQuantity: 240,
        yieldPercent: 88,
        wasteType: "Piel y raiz",
      },
      {
        id: "ri-3",
        rawMaterialId: "rm-arroz",
        name: "Arroz cocido base",
        unit: "g",
        grossQuantity: 420,
        yieldPercent: 100,
        wasteType: "Sin merma",
      },
    ],
  },
  {
    id: "rec-salmon",
    name: "Salmon grillado con crema citrica",
    category: "Fondo pescado",
    image:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80",
    portions: 3,
    prepTimeMinutes: 18,
    allergens: ["Pescado", "Lacteos"],
    procedure:
      "Porcionar salmon, grillar por piel, reducir crema citrica y servir con vegetales.",
    observations:
      "Mantener cadena de frio y controlar coccion para evitar resecado.",
    targetFoodCostPercent: 32,
    salePrice: 16900,
    ingredients: [
      {
        id: "ri-4",
        rawMaterialId: "rm-salmon",
        name: "Filete de salmon",
        unit: "g",
        grossQuantity: 640,
        yieldPercent: 78,
        wasteType: "Piel, espinas y recorte",
      },
      {
        id: "ri-5",
        rawMaterialId: "rm-crema",
        name: "Crema de leche",
        unit: "ml",
        grossQuantity: 280,
        yieldPercent: 92,
        wasteType: "Reduccion por evaporacion",
      },
    ],
  },
  {
    id: "rec-entrada",
    name: "Causa fria de camaron y palta",
    category: "Entrada fria",
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80",
    portions: 6,
    prepTimeMinutes: 16,
    allergens: ["Mariscos"],
    procedure:
      "Cocer base, prensar, montar con camaron descongelado en frio y palta laminada.",
    observations:
      "Mantener en frio hasta servicio y registrar lote de marisco.",
    targetFoodCostPercent: 28,
    salePrice: 8900,
    ingredients: [
      {
        id: "ri-6",
        rawMaterialId: "rm-camaron",
        name: "Camaron limpio",
        unit: "g",
        grossQuantity: 520,
        yieldPercent: 82,
        wasteType: "Glaseo y descongelado",
      },
      {
        id: "ri-7",
        rawMaterialId: "rm-palta",
        name: "Palta hass",
        unit: "g",
        grossQuantity: 460,
        yieldPercent: 64,
        wasteType: "Carozo y cascara",
      },
    ],
  },
];

export const products: Product[] = [
  {
    id: "prod-lomo",
    name: "Lomo salteado",
    categoryId: "cat-main",
    description: "Lomo, arroz, cebolla morada, salsa de la casa.",
    image:
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=80",
    price: 14900,
    available: true,
    prepTimeMinutes: 22,
    recipeId: "rec-lomo",
    modifiers: ["Sin cebolla", "Punto medio", "Bien cocido", "Extra queso"],
  },
  {
    id: "prod-salmon",
    name: "Salmon grillado",
    categoryId: "cat-main",
    description: "Salmon fresco, crema citrica y vegetales.",
    image:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80",
    price: 16900,
    available: true,
    prepTimeMinutes: 18,
    recipeId: "rec-salmon",
    modifiers: ["Sin lacteos", "Punto jugoso", "Punto cocido"],
  },
  {
    id: "prod-causa",
    name: "Causa camaron palta",
    categoryId: "cat-starter",
    description: "Entrada fria con camaron, palta y base especiada.",
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=80",
    price: 8900,
    available: true,
    prepTimeMinutes: 16,
    recipeId: "rec-entrada",
    modifiers: ["Sin palta", "Extra camaron", "Sin picante"],
  },
  {
    id: "prod-tabla",
    name: "Tabla caliente",
    categoryId: "cat-starter",
    description: "Porciones para compartir, salsas y panes.",
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
    price: 18900,
    available: false,
    prepTimeMinutes: 25,
    modifiers: ["Sin gluten", "Extra salsa", "Sin queso"],
  },
  {
    id: "prod-jugo",
    name: "Jugo natural",
    categoryId: "cat-bar",
    description: "Fruta fresca de temporada.",
    image:
      "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=900&q=80",
    price: 3900,
    available: true,
    prepTimeMinutes: 5,
    modifiers: ["Sin azucar", "Con hielo", "Sin hielo"],
  },
];

export const restaurantTables: RestaurantTable[] = [
  {
    id: "t-1",
    number: 1,
    seats: 2,
    zone: "Terraza",
    status: "free",
    server: "Valentina",
  },
  {
    id: "t-2",
    number: 2,
    seats: 4,
    zone: "Terraza",
    status: "occupied",
    server: "Valentina",
    currentOrderId: "ord-1",
    elapsedMinutes: 26,
    total: 42600,
  },
  {
    id: "t-3",
    number: 3,
    seats: 6,
    zone: "Salon",
    status: "reserved",
    server: "Matias",
  },
  {
    id: "t-4",
    number: 4,
    seats: 4,
    zone: "Salon",
    status: "occupied",
    server: "Camila",
    currentOrderId: "ord-2",
    elapsedMinutes: 14,
    total: 33800,
  },
  {
    id: "t-5",
    number: 5,
    seats: 2,
    zone: "Salon",
    status: "cleaning",
    server: "Camila",
    elapsedMinutes: 5,
  },
  {
    id: "t-6",
    number: 6,
    seats: 8,
    zone: "Comedor",
    status: "free",
    server: "Matias",
  },
  {
    id: "t-7",
    number: 7,
    seats: 4,
    zone: "Comedor",
    status: "occupied",
    server: "Valentina",
    currentOrderId: "ord-3",
    elapsedMinutes: 38,
    total: 57200,
  },
  {
    id: "t-8",
    number: 8,
    seats: 4,
    zone: "Comedor",
    status: "free",
    server: "Camila",
  },
  {
    id: "t-9",
    number: 9,
    seats: 2,
    zone: "Barra",
    status: "reserved",
    server: "Matias",
  },
  {
    id: "t-10",
    number: 10,
    seats: 4,
    zone: "Barra",
    status: "free",
    server: "Valentina",
  },
  {
    id: "t-11",
    number: 11,
    seats: 6,
    zone: "Salon",
    status: "free",
    server: "Camila",
  },
  {
    id: "t-12",
    number: 12,
    seats: 2,
    zone: "Salon",
    status: "occupied",
    server: "Matias",
    currentOrderId: "ord-4",
    elapsedMinutes: 8,
    total: 23800,
  },
];

export const orders: Order[] = [
  {
    id: "ord-1",
    number: "A-1048",
    tableNumber: 2,
    status: "preparing",
    waiter: "Valentina",
    createdAt: "2026-05-08T13:42:00-04:00",
    discount: 0,
    tip: 4260,
    total: 42600,
    items: [
      {
        id: "oi-1",
        productId: "prod-lomo",
        productName: "Lomo salteado",
        quantity: 2,
        unitPrice: 14900,
        modifiers: ["Punto medio", "Sin cebolla"],
        notes: "Mesa apurada, enviar fondos juntos.",
        station: "hot",
      },
      {
        id: "oi-2",
        productId: "prod-jugo",
        productName: "Jugo natural",
        quantity: 2,
        unitPrice: 3900,
        modifiers: ["Sin azucar"],
        station: "bar",
      },
    ],
  },
  {
    id: "ord-2",
    number: "A-1049",
    tableNumber: 4,
    status: "pending",
    waiter: "Camila",
    createdAt: "2026-05-08T13:54:00-04:00",
    discount: 1500,
    tip: 3380,
    total: 33800,
    items: [
      {
        id: "oi-3",
        productId: "prod-salmon",
        productName: "Salmon grillado",
        quantity: 2,
        unitPrice: 16900,
        modifiers: ["Punto jugoso"],
        notes: "Uno sin salsa sobre el plato.",
        station: "hot",
      },
    ],
  },
  {
    id: "ord-3",
    number: "A-1050",
    tableNumber: 7,
    status: "ready",
    waiter: "Valentina",
    createdAt: "2026-05-08T13:30:00-04:00",
    discount: 0,
    tip: 5720,
    total: 57200,
    items: [
      {
        id: "oi-4",
        productId: "prod-causa",
        productName: "Causa camaron palta",
        quantity: 4,
        unitPrice: 8900,
        modifiers: ["Extra camaron"],
        station: "cold",
      },
      {
        id: "oi-5",
        productId: "prod-jugo",
        productName: "Jugo natural",
        quantity: 4,
        unitPrice: 3900,
        modifiers: ["Con hielo"],
        station: "bar",
      },
    ],
  },
  {
    id: "ord-4",
    number: "A-1051",
    tableNumber: 12,
    status: "pending",
    waiter: "Matias",
    createdAt: "2026-05-08T14:02:00-04:00",
    discount: 0,
    tip: 2380,
    total: 23800,
    items: [
      {
        id: "oi-6",
        productId: "prod-lomo",
        productName: "Lomo salteado",
        quantity: 1,
        unitPrice: 14900,
        modifiers: ["Bien cocido", "Extra queso"],
        notes: "Alergia declarada a mariscos.",
        station: "hot",
      },
      {
        id: "oi-7",
        productId: "prod-causa",
        productName: "Causa camaron palta",
        quantity: 1,
        unitPrice: 8900,
        modifiers: ["Sin palta"],
        station: "cold",
      },
    ],
  },
];

export const employees: Employee[] = [
  {
    id: "emp-1",
    name: "Paula Contreras",
    role: "administrator",
    shift: "Administracion",
    status: "active",
    sales: 0,
    orders: 0,
  },
  {
    id: "emp-2",
    name: "Rodrigo Fuentes",
    role: "chef",
    shift: "Cocina AM",
    status: "active",
    sales: 0,
    orders: 18,
    kitchenAverage: 17,
  },
  {
    id: "emp-3",
    name: "Valentina Reyes",
    role: "waiter",
    shift: "Salon AM",
    status: "active",
    sales: 184700,
    orders: 12,
  },
  {
    id: "emp-4",
    name: "Camila Soto",
    role: "waiter",
    shift: "Salon AM",
    status: "break",
    sales: 126900,
    orders: 8,
  },
  {
    id: "emp-5",
    name: "Felipe Araya",
    role: "cashier",
    shift: "Caja AM",
    status: "active",
    sales: 311600,
    orders: 24,
  },
  {
    id: "emp-6",
    name: "Daniel Vega",
    role: "warehouse",
    shift: "Bodega",
    status: "active",
    sales: 0,
    orders: 0,
  },
];

export const purchases: Purchase[] = [
  {
    id: "pur-1",
    supplierId: "sup-1",
    supplierName: "Carnes Andinas",
    documentType: "invoice",
    documentNumber: "F-88219",
    date: "2026-05-07",
    total: 184000,
    status: "received",
  },
  {
    id: "pur-2",
    supplierId: "sup-2",
    supplierName: "Costa Azul",
    documentType: "invoice",
    documentNumber: "F-22018",
    date: "2026-05-08",
    total: 143600,
    status: "priced",
  },
  {
    id: "pur-3",
    supplierId: "sup-3",
    supplierName: "Huerta Local",
    documentType: "receipt",
    documentNumber: "B-5518",
    date: "2026-05-08",
    total: 48600,
    status: "received",
  },
];

export const cashMovements: CashMovement[] = [
  {
    id: "cm-1",
    type: "opening",
    description: "Apertura turno AM",
    method: "internal",
    amount: 120000,
    time: "09:00",
    responsible: "Felipe Araya",
  },
  {
    id: "cm-2",
    type: "sale",
    description: "Pago mesa 7",
    method: "debit",
    amount: 57200,
    time: "13:59",
    responsible: "Felipe Araya",
  },
  {
    id: "cm-3",
    type: "tip",
    description: "Propina mesa 7",
    method: "debit",
    amount: 5720,
    time: "13:59",
    responsible: "Felipe Araya",
  },
  {
    id: "cm-4",
    type: "withdrawal",
    description: "Retiro caja chica",
    method: "cash",
    amount: -20000,
    time: "14:10",
    responsible: "Supervisor",
  },
  {
    id: "cm-5",
    type: "advance",
    description: "Adelanto autorizado",
    method: "cash",
    amount: -15000,
    time: "14:15",
    responsible: "Supervisor",
  },
];

export const reportPoints: ReportPoint[] = [
  { label: "Lun", sales: 780000, foodCost: 248000, margin: 532000, orders: 74 },
  { label: "Mar", sales: 692000, foodCost: 226000, margin: 466000, orders: 68 },
  { label: "Mie", sales: 834000, foodCost: 257000, margin: 577000, orders: 81 },
  { label: "Jue", sales: 910000, foodCost: 293000, margin: 617000, orders: 88 },
  { label: "Vie", sales: 1134000, foodCost: 352000, margin: 782000, orders: 106 },
  { label: "Sab", sales: 1286000, foodCost: 398000, margin: 888000, orders: 119 },
  { label: "Dom", sales: 972000, foodCost: 301000, margin: 671000, orders: 92 },
];

export const educationSteps = [
  "Configurar roles y permisos antes de iniciar el turno.",
  "Crear mesas, asignar mesero y abrir pedido presencial.",
  "Agregar productos con modificadores y observaciones.",
  "Enviar comanda a cocina y medir tiempos por estacion.",
  "Cerrar cuenta con pago, propina, descuento y diferencia de caja.",
  "Revisar salida automatica de inventario y mermas.",
  "Comparar costo tecnico, precio sugerido y rentabilidad real.",
];
